---
- name: Install nginx package
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Start and enable nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: started
    enabled: true
