- name: Testing Roles
  hosts: all
  become: true
  roles:
#    - common
#    - adduser
#    - jellyfin
#    - plex
    - caddy
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
