- name: Testing Roles
  hosts: all
  roles:
#    - common
#    - adduser
#    - jellyfin
#    - plex
#    - caddy
#    - dotfiles
    - ufw
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
