---
- name: Prepare host
  ansible.builtin.include_tasks: prepare_host.yml

- name: Install jellyfin
  ansible.builtin.include_tasks: install.yml

- name: Configure jellyfin
  ansible.builtin.include_tasks: config.yml

- name: Configure fail2ban
  ansible.builtin.include_tasks: fail2ban.yml
  when: jellyfin_fail2ban_enabled | bool

- name: Configure webserver
  ansible.builtin.include_tasks: webconfig/main.yml

- name: Enable and start jellyfin
  ansible.builtin.systemd:
    name: jellyfin.service
    state: started
    enabled: true
  changed_when: false
