#SPDX-License-Identifier: MIT-0
---
# handlers file for plex
- name: Restart plexmediaserver
  ansible.builtin.systemd:
    name: plexmediaserver.service
    state: restarted
  listen: restart_plex

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban.service
    state: restarted
  listen: Restart fail2ban

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
  listen: reload_nginx

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: systemd_daemon_reload
