---
- name: Install the basics
  ansible.builtin.package:
    name:
      - sudo
      - python3-libdnf5
      - net-tools
      - curl
      - ufw
      - nginx
      - htop
      - samba
      - unzip
      - zip
    state: latest
