---
- name: remove cockpit message (Redhat)
  file:
     path: /etc/motd.d/cockpit
     state: absent
  when: ansible_os_family == "RedHat"

- name: disable update-motd.d (Debian)
  file:
     path: /etc/update-motd.d/
     state: touch
     mode: ugo-x
  when: ansible_os_family == "Debian"

- name: add motd message (RedHat Based)
  copy:
    src: /home/tdavi1/Desktop/ansible_test/test-lab/roles/common/templates/motd.j2
    dest: /etc/motd.d/motd
    owner: root
    group: root
    force: yes
    mode: u=rw,g=r,o=r
  when: ansible_os_family == "RedHat"


- name: add motd message (Debian Based)
  copy:
    src: /home/tdavi1/Desktop/ansible_test/test-lab/roles/common/templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    force: yes
    mode: u=rw,g=r,o=r
  when: ansible_os_family == "Debian"
...
