---
- name:  Install PlexMediaServer
  apt:
    name: gpg
    state: present
    update_cache: true

- name: Check for plex.gpg exists
  stat:
    path: /etc/apt/trusted.gpg.d/plex.gpg
  register: stat_result

- name: Download Repository Key
  shell: "wget -O- https://downloads.plex.tv/plex-keys/PlexSign.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/plex.gpg"
  when: not stat_result.stat.exists

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/plex.gpg] https://downloads.plex.tv/repo/deb public main"
    state: present

- name: Install Plex Server
  apt:
    name: plexmediaserver
    state: present
    update_cache: "true"

- name: Start and enable Plex service
  service:
    name: plexmediaserver
    state: started
    enabled: true
