- name: Install and Start Nginx
  host: all
  become: yes
  tasks:
    - name: Install Nginx Package
      dnf:
        name: nginx
        state: present
    - name: Ensure Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
