---
- name: Initial setup for proxmox servers
  hosts: proxmox
  user: root
  become: true

  tasks:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - aptitude
          - curl
          - nano
          - vim
          - git
          - ufw
          - neofetch
          - python3-proxmoxer
          - python3-requests
        state: latest
        update_cache: true

    - name: Basic security hardening
      import_tasks: security.yml

    - name: Deploy VMs
      import_tasks: machines.yml
